import type { TourStep, OSChoice } from '@/types/onboarding';

const tourSteps: TourStep[] = [
  {
    id: 'marketplace-install',
    targetId: 'leadscout-install-btn',
    title: 'Hire your first AI agent',
    description: 'LeadScout qualifies leads and scores prospects automatically. Add it to your workspace now.',
    instruction: 'Click Install to hire LeadScout',
    position: 'bottom',
    page: '/space/marketplace',
    passthrough: true,
  },
  {
    id: 'nav-to-integrations',
    targetId: 'nav-integrations',
    title: 'Connect your tools',
    description: 'Your agents need access to the apps you already use. Let\'s set that up.',
    instruction: 'Click Integrations in the sidebar',
    position: 'right',
    page: '/space/marketplace',
  },
  {
    id: 'integrations-explain',
    targetId: null,
    title: 'Your integration hub',
    description: 'This is where you authorise the tools your AI agents can access — Slack, Google, Salesforce, and more. Agents can only touch what you explicitly connect here.',
    position: 'center',
    page: '/space/integrations',
    showContinue: true,
  },
  {
    id: 'nav-to-activity',
    targetId: 'nav-activity',
    title: 'See what\'s happening',
    description: 'Every action your agents take is logged in real time.',
    instruction: 'Click Activity in the sidebar',
    position: 'right',
    page: '/space/integrations',
  },
  {
    id: 'activity-first-row',
    targetId: 'first-activity-row',
    title: 'Live activity feed',
    description: 'Every tool call, decision, and task your agents perform appears here instantly.',
    instruction: 'Click an entry to inspect it',
    position: 'bottom',
    page: '/space/activity',
    passthrough: true,
  },
  {
    id: 'activity-explain',
    targetId: null,
    title: 'Full visibility, always',
    description: 'You can see exactly what each agent did, why, and what changed. Nothing happens in a black box.',
    position: 'center',
    page: '/space/activity',
    showContinue: true,
  },
  {
    id: 'nav-to-chats',
    targetId: 'nav-chats',
    title: 'Talk to your agents',
    description: 'Your agents are conversational too — ask them anything, delegate tasks, get live updates.',
    instruction: 'Click Chats in the sidebar',
    position: 'right',
    page: '/space/activity',
  },
  {
    id: 'chats-ticketsolver',
    targetId: 'ticketsolver-chat',
    title: 'Your AI team in action',
    description: 'Every agent you hire gets a dedicated chat thread. TicketSolver just auto-resolved 8 support tickets — click to see exactly what it did.',
    instruction: 'Click TicketSolver to open the thread',
    position: 'right',
    page: '/space/chats',
    passthrough: true,
  },
  {
    id: 'tour-complete',
    targetId: null,
    title: "You're all set",
    description: 'Your workspace is live. Head to the marketplace anytime to grow your AI team.',
    position: 'center',
    page: '/space/chats',
    isFinal: true,
  },
];

export function getTourSteps(_osChoice: OSChoice | null): TourStep[] {
  return tourSteps;
}
