steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/lets-get-grooooooooovy/groovy-docker/groovy-frontend:$COMMIT_SHA'
      - '-t'
      - 'europe-west2-docker.pkg.dev/lets-get-grooooooooovy/groovy-docker/groovy-frontend:latest'
      - '.'

images:
  - 'europe-west2-docker.pkg.dev/lets-get-grooooooooovy/groovy-docker/groovy-frontend'
